project:
  type: website
  output-dir: docs

website:
  title: "Ellie Schomberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - diveintosustainability.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

