project:
  type: website
  output-dir: docs

website:
  title: "Ellie Schomberg"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - diveintosustainability.qmd
      - href: media/Resume-Ellie Schomberg (2).pdf
        text: Resume
        target: _blank

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

